In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train = pd.read_csv("/content/drive/My Drive/DSN AIBootcamp 2020/Train (1).csv")

test = pd.read_csv("/content/drive/My Drive/DSN AIBootcamp 2020/Test.csv")


sample_sub = pd.read_csv("/content/drive/My Drive/DSN AIBootcamp 2020/SampleSubmission.csv")

In [ ]:
def get_column_missing(df):
    col = df.isnull().any()
    missing_col = col[col== True].index
    return missing_col

In [ ]:
get_column_missing(train)

Index(['form_field1', 'form_field2', 'form_field3', 'form_field4',
       'form_field5', 'form_field6', 'form_field7', 'form_field8',
       'form_field9', 'form_field10', 'form_field11', 'form_field12',
       'form_field13', 'form_field15', 'form_field16', 'form_field17',
       'form_field18', 'form_field19', 'form_field20', 'form_field21',
       'form_field22', 'form_field23', 'form_field24', 'form_field25',
       'form_field26', 'form_field27', 'form_field28', 'form_field29',
       'form_field30', 'form_field31', 'form_field32', 'form_field33',
       'form_field34', 'form_field35', 'form_field36', 'form_field37',
       'form_field38', 'form_field39', 'form_field40', 'form_field41',
       'form_field42', 'form_field43', 'form_field44', 'form_field45',
       'form_field46', 'form_field48', 'form_field49', 'form_field50'],
      dtype='object')

In [ ]:
train['form_field47'] = [1 if i == 'charge' else 0 for i in train['form_field47']]

In [ ]:
train['form_field47'].unique()

array([1, 0])

In [ ]:
train['default_status'] = [1 if i == 'yes' else 0 for i in train['default_status']]

In [ ]:
train['default_status'].unique()

array([0])

In [ ]:
train = train.fillna(train.mean())

In [ ]:
test['form_field47'] = [1 if i == 'charge' else 0 for i in test['form_field47']]

In [ ]:
test = test.fillna(test.mean())

In [ ]:
test = test.drop("Applicant_ID", axis = 1)

In [ ]:
X = train.drop(columns = ['default_status', 'Applicant_ID'], axis = 1)

y = train.default_status


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size=0.3, random_state=42)

In [ ]:
 from sklearn.ensemble import RandomForestClassifier

 clf = RandomForestClassifier(n_estimators = 100)

In [ ]:
clf.fit(X_train, y_train)

In [ ]:
parameters = {'n_estimators' : (50,70,90,100, 150, 200)
              # , 'criterion' : ('gini', 'entropy')
              , 'max_depth' : (3,5,7,9,10)
              # , 'max_features' : ('auto', 'sqrt')
              , 'learning_rate' : (0.1, 0.01, 0.001)
              #, 'min_weight_fraction_leaf' : (0.0,0.1,0.2,0.3)
             }

In [ ]:
from sklearn.model_selection import GridSearchCV

RF_grid  = GridSearchCV(RandomForestClassifier(n_jobs = -1, oob_score= False), param_grid = parameters, cv = 3, verbose = True)


In [ ]:

RF_grid_model = RF_grid.fit(X_train, y_train)

Fitting 3 folds for each of 360 candidates, totalling 1080 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


In [ ]:

RF_grid_model.best_estimator_

In [ ]:
RF_grid_model.best_score_

In [ ]:
RF_Model = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=90, n_jobs=-1,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [ ]:

RF_Model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=90, n_jobs=-1,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [ ]:
RF_Model.score(X_train, y_train)

0.8490051020408164

In [ ]:

best_feat = pd.DataFrame({'Features': X_train.columns,'Importance': RF_Model.feature_importances_})
best_feat.sort_values('Importance', ascending = False)

Features  Importance
0    form_field1    0.136107
17  form_field18    0.058515
46  form_field47    0.047430
23  form_field24    0.046896
1    form_field2    0.046706
41  form_field42    0.044316
15  form_field16    0.034450
16  form_field17    0.029746
20  form_field21    0.028365
27  form_field28    0.027896
7    form_field8    0.026953
24  form_field25    0.025248
9   form_field10    0.024739
5    form_field6    0.021668
6    form_field7    0.019893
31  form_field32    0.019193
37  form_field38    0.018744
28  form_field29    0.018416
2    form_field3    0.016918
25  form_field26    0.016753
8    form_field9    0.016669
26  form_field27    0.016333
21  form_field22    0.015281
44  form_field45    0.014652
35  form_field36    0.013112
36  form_field37    0.012551
48  form_field49    0.012102
42  form_field43    0.011504
47  form_field48    0.010860
43  form_field44    0.010797
10  form_field11    0.010644
49  form_field50    0.010406
22  form_field23    0.010286
32  form_field33    0.010268
29  form_field30    0.009781
14  form_field15    0.009159
11  form_field12    0.008973
39  form_field40    0.008828
12  form_field13    0.008659
18  form_field19    0.008571
3    form_field4    0.007540
34  form_field35    0.007486
30  form_field31    0.007427
13  form_field14    0.007365
33  form_field34    0.006878
40  form_field41    0.006716
19  form_field20    0.006317
38  form_field39    0.004282
45  form_field46    0.004156
4    form_field5    0.003445

In [ ]:
y_pred = RF_Model.predict(test).astype(int)

In [ ]:
y_pred.shape

(24000,)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
sample_sub.head()

Applicant_ID  default_status
0  Apcnt_1000032               1
1  Apcnt_1000048               1
2  Apcnt_1000052               1
3  Apcnt_1000076               1
4  Apcnt_1000080               1

In [ ]:
sample_sub.default_status = y_pred

In [ ]:
sample_sub.to_csv("sub3.csv", index = False)

In [ ]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [10,30,50,70,90,100],
            'max_depth' : [3,5,7,9,10],
            'max_features' : ['auto', 'sqrt'],
            'min_samples_split' : [2,4,6]


        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}


# {'n_estimators' : (10,30,50,70,90,100)
#               , 'criterion' : ('gini', 'entropy')
#               , 'max_depth' : (3,5,7,9,10)
#               , 'max_features' : ('auto', 'sqrt')
#               , 'min_samples_split' : (2,4,6)
#               #, 'min_weight_fraction_leaf' : (0.0,0.1,0.2,0.3)
#              }

In [ ]:

scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X_train, y_train)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

In [ ]:
from sklearn import svm

In [ ]:

model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test, y_test)

0.7547619047619047

In [ ]:
from sklearn.model_selection import cross_val_score
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),X_train, y_train, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores


In [ ]:
pip install lightgbm

In [ ]:
import lightgbm as lgb
clf = lgb.LGBMClassifier(n_estimators=150)
clf.fit(X_train, y_train)



LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=150, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
prediction = clf.predict_proba(test)

In [ ]:
prediction

array([[1.e+00, 1.e-15],
       [1.e+00, 1.e-15],
       [1.e+00, 1.e-15],
       ...,
       [1.e+00, 1.e-15],
       [1.e+00, 1.e-15],
       [1.e+00, 1.e-15]])

In [ ]:
prediction = prediction[:, 1]

array([1.e-15, 1.e-15, 1.e-15, ..., 1.e-15, 1.e-15, 1.e-15])

In [ ]:
sample_sub.default_status = prediction

In [ ]:
sample_sub.to_csv("sub4.csv", index = False)

In [ ]:
parameters = {'n_estimators' : (50,70,90,100, 150, 200)
              # , 'criterion' : ('gini', 'entropy')
              , 'max_depth' : (3,5,7,9,10)
              # , 'max_features' : ('auto', 'sqrt')
              , 'learning_rate' : (0.1, 0.01, 0.001)
              #, 'min_weight_fraction_leaf' : (0.0,0.1,0.2,0.3)
             }

In [ ]:
from sklearn.model_selection import GridSearchCV

Lgbm_grid  = GridSearchCV(lgb.LGBMClassifier(n_jobs = -1, oob_score= False), param_grid = parameters, cv = 3, verbose = True)

In [ ]:
lgbm_grid_model = Lgbm_grid.fit(X_train, y_train)

Fitting 3 folds for each of 90 candidates, totalling 270 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 270 out of 270 | elapsed:   48.7s finished


In [ ]:
lgbm_grid_model.best_score_

1.0

In [ ]:
lgbm_grid_model.best_estimator_

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=3,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=50, n_jobs=-1, num_leaves=31, objective=None,
               oob_score=False, random_state=None, reg_alpha=0.0,
               reg_lambda=0.0, silent=True, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [ ]:
clf = lgb.LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=3,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=50, n_jobs=-1, num_leaves=31, objective=None,
               oob_score=False, random_state=None, reg_alpha=0.0,
               reg_lambda=0.0, silent=True, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

clf.fit(X_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=3,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=50, n_jobs=-1, num_leaves=31, objective=None,
               oob_score=False, random_state=None, reg_alpha=0.0,
               reg_lambda=0.0, silent=True, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [ ]:
prediction = clf.predict_proba(test)[:, 1]

In [ ]:
sample_sub.default_status = prediction
sample_sub.to_csv("sub5.csv", index = False)